### ISSUE TITLE
Update Mobile Takeover bit

### ISSUE THREAD

**Issue by reelcitizen** [gamernetwork/gn-ad-spec-gh#1]
From Barbara...

"any chance we can make an amend to the mobile section? So I was thinking instead of having mobile fishbowl and sticky leaderboard separately we could bring them together as a mobile takeover, like the desktop? It's mostly because the clients always miss the leaderboard because it's separate, that way we'd avoid that"

**Comment by richardbristow** [comment]
Made these changes in https://github.com/gamernetwork/gn-ad-spec/commit/809c066a148447b36d3a09854947da99896d0a9d
